package com.realestate.enums;

public enum AttributeType {
    NUMBER_OF_ROOMS, USABLE_SURFACE, PARTITIONING, FLOOR, CONSTRUCTION_YEAR, TIPIMOBIL, STATE, FURNISHED_EQUIPPED, NUMBER_OF_BATHROOMS, PARKING, TOTAL_SURFACE, AMENITIES, CLASSIFICATION, FRONTSTRADAL
}